### ISSUE TITLE
Not sure Lannister's power is working

### ISSUE THREAD

**Issue by hcarver** [tijptjik/ascension#29]
I have non-integer points for some episodes, and I don't think that's possible without performance penalties (which I don't think I should have).

**Comment by tijptjik** [comment]
To clarify your house abilities - they don't get a performance penalty when running missions, but if one of your characters was injured, say:

![image](https://cloud.githubusercontent.com/assets/645283/15996676/29b57c92-315d-11e6-9bb4-97724bfc8ded.png)

then that character would have 75 HP less and would multiply their awarded score by 0.75 instead of the 1 at full health.

Hope that clarifies it!
